# Generated by Django 5.2.3 on 2025-06-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(help_text='URL для сбора информации')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(help_text='Загрузка CPU')),
                ('memory', models.CharField(help_text='Использование память', max_length=10)),
                ('disk', models.CharField(help_text='Использование диска', max_length=10)),
                ('uptime', models.CharField(help_text='Время работы', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.machine')),
            ],
        ),
    ]
