# Generated by Django 5.2.3 on 2025-06-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='cpu',
            field=models.FloatField(help_text='Загрузка CPU'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='disk',
            field=models.FloatField(help_text='Использование диска'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='memory',
            field=models.FloatField(help_text='Использование память'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cpu', 'Cpu'), ('mem', 'Memory'), ('disk', 'Disk')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.machine')),
            ],
        ),
    ]
